# Generated by Django 3.1.3 on 2020-12-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='tipo_autor',
            field=models.CharField(blank=True, choices=[('Cliente', 'Cliente'), ('Administrador', 'Administrador')], default='Cliente', max_length=20, null=True, verbose_name='Tipo de usuario'),
        ),
    ]
