# Generated by Django 3.1.3 on 2020-12-03 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_autor_tipo_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrito',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.autor')),
                ('issn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.libro')),
            ],
            options={
                'verbose_name': 'Articulo',
                'verbose_name_plural': 'Articulos',
            },
        ),
    ]
