# Generated by Django 3.1.3 on 2020-11-25 02:45

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0002_auto_20201119_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='nacionalidad',
        ),
        migrations.AddField(
            model_name='autor',
            name='cedula',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Cedula'),
        ),
        migrations.AddField(
            model_name='autor',
            name='ciudad',
            field=models.CharField(choices=[('Armenia', 'Armenia'), ('Barranquilla', 'Barranquilla'), ('Bello', 'Bello'), ('Bogotá', 'Bogotá'), ('Bucaramanga', 'Bucaramanga'), ('Cali', 'Cali'), ('Cartagena', 'Cartagena'), ('Cúcuta', 'Cúcuta'), ('Ibagué', 'Ibagué'), ('Manizales', 'Manizales'), ('Medellín', 'Medellín'), ('Montería', 'Montería'), ('Neiva', 'Neiva'), ('Cartagena', 'Cartagena'), ('Pasto', 'Pasto'), ('Pereira', 'Pereira'), ('Santa Marta', 'Santa Marta'), ('Soacha', 'Soacha'), ('Soledad', 'Soledad'), ('Valledupar', 'Valledupar'), ('Villavicencio', 'Villavicencio')], default='1', max_length=200, verbose_name='Ciudad de residencia'),
        ),
        migrations.AddField(
            model_name='autor',
            name='contrasena',
            field=models.CharField(max_length=30, null=True, verbose_name='Contrasena'),
        ),
        migrations.AddField(
            model_name='autor',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='autor',
            name='genero',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], max_length=15, null=True, verbose_name='Genero'),
        ),
        migrations.AddField(
            model_name='autor',
            name='nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='autor',
            name='suscripcion',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Suscribirme a noticias'),
        ),
        migrations.AddField(
            model_name='autor',
            name='temas_preferidos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Historia y Geografía', 'Historia y Geografía'), ('Narrativa', 'Narrativa'), ('Juvenil', 'Juvenil'), ('Ciencias físicas', 'Ciencias físicas'), ('Infantil', 'Infantil'), ('Ciencias Sociales y política', 'Ciencias Sociales y política'), ('Medicina y salud', 'Medicina y salud'), ('Filosofía', 'Filosofía'), ('Arquitectura', 'Arquitectura'), ('Arte', 'Arte'), ('Gastronomía', 'Gastronomía'), ('Varios', 'Varios')], max_length=157, null=True, verbose_name='Temas de preferencia'),
        ),
        migrations.AddField(
            model_name='autor',
            name='usuario',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nombre de usuario'),
        ),
    ]
