# Generated by Django 3.1.3 on 2020-12-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='id_autor',
            field=models.CharField(max_length=30, null=True, verbose_name='ID autor'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='issn',
            field=models.CharField(max_length=30, null=True, verbose_name='ISSN'),
        ),
    ]
