# Generated by Django 3.1.3 on 2020-11-26 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0003_auto_20201125_0245'),
    ]

    operations = [
        migrations.CreateModel(
            name='tarjeta',
            fields=[
                ('id_tarjeta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True, verbose_name='Nombre de la tarjeta')),
                ('caducidad', models.DateField(null=True, verbose_name='Fecha de caducidad')),
                ('tipo_tarjeta', models.CharField(default='Credito', max_length=30, verbose_name='Tipo de tarjeta')),
                ('saldo', models.IntegerField(null=True, verbose_name='Saldo')),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libro.autor')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
            },
        ),
    ]
