# Generated by Django 3.1.3 on 2020-11-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_tarjeta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo_tarjeta',
            field=models.CharField(choices=[('Debito', 'Debito'), ('Credito', 'Credito')], default='Credito', max_length=30, verbose_name='Tipo de tarjeta'),
        ),
    ]
